# fly.toml app configuration file generated for meshiuchi-back on 2025-04-27T21:55:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meshiuchi-back'
primary_region = 'nrt'

[build]
  dockerfile = './back/Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  size = 'shared-cpu-1x'
