# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

production:
  # ───── アプリ本体 ─────
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>   # ← ここだけで十分
    sslmode: require                 # Heroku/Fly 互換（任意）

  # ───── Action Cable ─────
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
