# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary: &dev_primary
    <<: *default
    host: db
    database: meshiuchi_development
    username: user
    password: password
  queue:
    <<: *dev_primary
    migrations_paths: db/queue_migrate
  cable:
    <<: *dev_primary
    migrations_paths: db/cable_migrate
  cache:                          # ←★追加
    <<: *dev_primary
    migrations_paths: db/cache_migrate

test:
  <<: *dev_primary

production:
  primary: &prod_primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
  queue:
    <<: *prod_primary
    migrations_paths: db/queue_migrate
  cable:
    <<: *prod_primary
    migrations_paths: db/cable_migrate
  cache:                          # ←★追加
    <<: *prod_primary
    migrations_paths: db/cache_migrate
