# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host:     <%= ENV.fetch("PGHOST", "localhost") %>

production:
  primary: &prod_primary           
    <<: *default
    database: <%= ENV.fetch("PGDATABASE", "meshiuchi_production") %>

  cable:                               
    <<: *prod_primary                    
    database: <%= ENV.fetch("PGDATABASE", "meshiuchi_production") %>
    migrations_paths: db/cable_migrate
