# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host:     <%= ENV.fetch("PGHOST", "localhost") %>

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "meshiuchi_production") %>
  cable:
    <<: *default
    database: <%= ENV.fetch("PGDATABASE", "meshiuchi_production") %>
